# create environment : conda env create -f environment.yml
# update dependencies: conda env update -f environment.yml
# remove environment : conda env remove -n ARIA-tools
# enter  environment : conda activate ARIA-tools
# exit   environment : conda deactivate
name: ARIA-tools
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - asf_search
  - cartopy
  - gdal>=3.4.2
  - h5py
  - joblib
  - matplotlib
  - netcdf4
  - pandas
  - pyproj
  - requests
  - rise
  - scipy
  - shapely
  #for ARIA-tools-docs
  - jupyterlab
  - jupyter_contrib_nbextensions
